//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvropskoPrvenstvoUKosarci2.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EvropskoPrvenstvoUKosarciEntities1 : DbContext
    {
        public EvropskoPrvenstvoUKosarciEntities1()
            : base("name=EvropskoPrvenstvoUKosarciEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Grad> Grad { get; set; }
        public virtual DbSet<Grupa> Grupa { get; set; }
        public virtual DbSet<Hala> Hala { get; set; }
        public virtual DbSet<Igrac> Igrac { get; set; }
        public virtual DbSet<Korisnici> Korisnici { get; set; }
        public virtual DbSet<Pozicija> Pozicija { get; set; }
        public virtual DbSet<Reprezentacija> Reprezentacija { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Utakmice> Utakmice { get; set; }
        public virtual DbSet<Zemlje> Zemlje { get; set; }
        public virtual DbSet<ZemljeGradovi> ZemljeGradovi { get; set; }
    }
}
