//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvropskoPrvenstvoUKosarci2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Igrac
    {
        public int IgracId { get; set; }
        public string Ime { get; set; }
        public string Prezime { get; set; }
        public Nullable<int> Visina { get; set; }
        [Display(Name ="Težina")]
        public Nullable<int> Tezina { get; set; }
        [Display(Name = "Broj dresa")]
        public Nullable<int> BrojDresa { get; set; }
        [Display(Name = "Pozicija")]
        public Nullable<int> PozicijaId { get; set; }
        [Display(Name = "Reprezentacija")]
        public Nullable<int> ReprezentacijaId { get; set; }

        [Display(Name = "Pozicija")]
        public virtual Pozicija Pozicija { get; set; }
        [Display(Name = "Reprezentacija")]
        public virtual Reprezentacija Reprezentacija { get; set; }
    }
}
