//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvropskoPrvenstvoUKosarci2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Reprezentacija
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Reprezentacija()
        {
            this.Igrac = new HashSet<Igrac>();
            this.Utakmice = new HashSet<Utakmice>();
            this.Utakmice1 = new HashSet<Utakmice>();
        }
    
        public int ReprezentacijaId { get; set; }
        [Display(Name = "Naziv reprezentacije")]
        public string NazivReprezentacija { get; set; }
        public Nullable<int> ZemljeId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Igrac> Igrac { get; set; }
        public virtual Zemlje Zemlje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utakmice> Utakmice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Utakmice> Utakmice1 { get; set; }
    }
}
