//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvropskoPrvenstvoUKosarci2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ZemljeGradovi
    {
        public int ZemljeGradoviId { get; set; }
        public Nullable<int> ZemljeId { get; set; }
        public Nullable<int> GradId { get; set; }
    
        public virtual Grad Grad { get; set; }
        public virtual Zemlje Zemlje { get; set; }
    }
}
